export const dummyProducts = [
  {
    name: "iPhone 14 Pro",
    price: 119999,
    description: "Apple iPhone 14 Pro with A16 Bionic chip, 128GB storage.",
    postingDate: new Date(),
    zipCode: "560001",
    seller: null,
    verified: true,
    category: "Mobiles",
    district: "Bangalore Urban",
    city: "Bangalore",
    state: "Karnataka",
    invoice: "",
    images: ["iphone14pro.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Dell XPS 13",
    price: 104999,
    description: "Compact laptop with Intel i7, 16GB RAM, and 512GB SSD.",
    postingDate: new Date(),
    zipCode: "110001",
    seller: null,
    verified: true,
    category: "Laptops",
    district: "New Delhi",
    city: "New Delhi",
    state: "Delhi",
    invoice: "",
    images: ["dellxps13.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Adidas Running Shoes",
    price: 4999,
    description: "Lightweight and comfortable shoes for daily running.",
    postingDate: new Date(),
    zipCode: "400001",
    seller: null,
    verified: false,
    category: "Fashion",
    district: "Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    invoice: "",
    images: ["adidasrun.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Sony WH-1000XM5 Headphones",
    price: 29999,
    description: "Noise-cancelling wireless headphones with 30-hour battery.",
    postingDate: new Date(),
    zipCode: "600001",
    seller: null,
    verified: true,
    category: "Electronics",
    district: "Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    invoice: "",
    images: ["sonywh1000xm5.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Wooden Study Table",
    price: 8999,
    description: "Ergonomic wooden study table with drawers and storage.",
    postingDate: new Date(),
    zipCode: "700001",
    seller: null,
    verified: false,
    category: "Furniture",
    district: "Kolkata",
    city: "Kolkata",
    state: "West Bengal",
    invoice: "",
    images: ["studytable.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Hero Splendor Plus",
    price: 65000,
    description: "Reliable commuter bike with great mileage and low maintenance.",
    postingDate: new Date(),
    zipCode: "500001",
    seller: null,
    verified: true,
    category: "Automobiles",
    district: "Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    invoice: "",
    images: ["herosplendor.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Yonex Badminton Racket",
    price: 3499,
    description: "Professional-grade badminton racket for competitive play.",
    postingDate: new Date(),
    zipCode: "302001",
    seller: null,
    verified: true,
    category: "Sports",
    district: "Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    invoice: "",
    images: ["yonex.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Guitar - Fender Stratocaster",
    price: 54999,
    description: "Electric guitar with excellent tone and build quality.",
    postingDate: new Date(),
    zipCode: "411001",
    seller: null,
    verified: true,
    category: "Musical Instruments",
    district: "Pune",
    city: "Pune",
    state: "Maharashtra",
    invoice: "",
    images: ["fenderstrato.jpg"],
    requests: [],
    soldTo: null,
    isRental: true,
  },
  {
    name: "Levi’s Denim Jacket",
    price: 6999,
    description: "Classic denim jacket made from premium cotton.",
    postingDate: new Date(),
    zipCode: "201001",
    seller: null,
    verified: false,
    category: "Clothes",
    district: "Ghaziabad",
    city: "Ghaziabad",
    state: "Uttar Pradesh",
    invoice: "",
    images: ["levisjacket.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Samsung 55-inch 4K Smart TV",
    price: 74999,
    description: "Smart TV with crystal display and built-in streaming apps.",
    postingDate: new Date(),
    zipCode: "641001",
    seller: null,
    verified: true,
    category: "Electronics",
    district: "Coimbatore",
    city: "Coimbatore",
    state: "Tamil Nadu",
    invoice: "",
    images: ["samsungtv.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Canon EOS 200D DSLR",
    price: 59999,
    description: "Compact DSLR camera with 24.1MP sensor and dual pixel autofocus.",
    postingDate: new Date(),
    zipCode: "226001",
    seller: null,
    verified: true,
    category: "Electronics",
    district: "Lucknow",
    city: "Lucknow",
    state: "Uttar Pradesh",
    invoice: "",
    images: ["canon200d.jpg"],
    requests: [],
    soldTo: null,
    isRental: true,
  },
  {
    name: "IKEA Recliner Chair",
    price: 15999,
    description: "Comfortable recliner chair ideal for living rooms.",
    postingDate: new Date(),
    zipCode: "380001",
    seller: null,
    verified: false,
    category: "Furniture",
    district: "Ahmedabad",
    city: "Ahmedabad",
    state: "Gujarat",
    invoice: "",
    images: ["recliner.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "MacBook Air M2",
    price: 134999,
    description: "Apple MacBook Air with M2 chip, 8GB RAM, and 256GB SSD.",
    postingDate: new Date(),
    zipCode: "160001",
    seller: null,
    verified: true,
    category: "Laptops",
    district: "Chandigarh",
    city: "Chandigarh",
    state: "Punjab",
    invoice: "",
    images: ["macbookairm2.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "HP Pavilion Gaming Laptop",
    price: 89999,
    description: "Gaming laptop with Ryzen 7 and RTX 3050 GPU.",
    postingDate: new Date(),
    zipCode: "751001",
    seller: null,
    verified: false,
    category: "Laptops",
    district: "Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    invoice: "",
    images: ["hppavilion.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Nike Air Max",
    price: 7999,
    description: "Premium sneakers designed for comfort and style.",
    postingDate: new Date(),
    zipCode: "302002",
    seller: null,
    verified: true,
    category: "Fashion",
    district: "Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    invoice: "",
    images: ["nikeairmax.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Cricket Bat - SG King Cobra",
    price: 8499,
    description: "English willow cricket bat used by professionals.",
    postingDate: new Date(),
    zipCode: "462001",
    seller: null,
    verified: true,
    category: "Sports",
    district: "Bhopal",
    city: "Bhopal",
    state: "Madhya Pradesh",
    invoice: "",
    images: ["sgbat.jpg"],
    requests: [],
    soldTo: null,
    isRental: true,
  },
  {
    name: "Samsung Galaxy S23 Ultra",
    price: 124999,
    description: "Flagship Samsung phone with S Pen and 200MP camera.",
    postingDate: new Date(),
    zipCode: "122001",
    seller: null,
    verified: true,
    category: "Mobiles",
    district: "Gurgaon",
    city: "Gurgaon",
    state: "Haryana",
    invoice: "",
    images: ["s23ultra.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Honda Activa 6G",
    price: 78000,
    description: "Best-selling scooter in India with excellent mileage.",
    postingDate: new Date(),
    zipCode: "695001",
    seller: null,
    verified: false,
    category: "Automobiles",
    district: "Thiruvananthapuram",
    city: "Thiruvananthapuram",
    state: "Kerala",
    invoice: "",
    images: ["activa6g.jpg"],
    requests: [],
    soldTo: null,
    isRental: true,
  },
  {
    name: "Wooden Dining Table Set",
    price: 24999,
    description: "6-seater dining table with solid teak wood finish.",
    postingDate: new Date(),
    zipCode: "141001",
    seller: null,
    verified: true,
    category: "Furniture",
    district: "Ludhiana",
    city: "Ludhiana",
    state: "Punjab",
    invoice: "",
    images: ["diningtable.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Tata Tiago 2021 Model",
    price: 575000,
    description: "Pre-owned Tata Tiago with only 20,000 km driven.",
    postingDate: new Date(),
    zipCode: "380015",
    seller: null,
    verified: true,
    category: "Automobiles",
    district: "Ahmedabad",
    city: "Ahmedabad",
    state: "Gujarat",
    invoice: "",
    images: ["tatatiago.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Acoustic Guitar - Yamaha F310",
    price: 9999,
    description: "Beginner-friendly acoustic guitar with natural finish.",
    postingDate: new Date(),
    zipCode: "700021",
    seller: null,
    verified: true,
    category: "Musical Instruments",
    district: "Kolkata",
    city: "Kolkata",
    state: "West Bengal",
    invoice: "",
    images: ["yamahaF310.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Samsung Refrigerator 300L",
    price: 28999,
    description: "Double-door refrigerator with inverter compressor.",
    postingDate: new Date(),
    zipCode: "248001",
    seller: null,
    verified: true,
    category: "Electronics",
    district: "Dehradun",
    city: "Dehradun",
    state: "Uttarakhand",
    invoice: "",
    images: ["samsungfridge.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Formal Shirt - Peter England",
    price: 1999,
    description: "Slim fit formal shirt made of breathable cotton fabric.",
    postingDate: new Date(),
    zipCode: "500081",
    seller: null,
    verified: false,
    category: "Clothes",
    district: "Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    invoice: "",
    images: ["petershirt.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Macmillan Physics Book - Class 12",
    price: 799,
    description: "Reference physics book with detailed concept coverage.",
    postingDate: new Date(),
    zipCode: "462003",
    seller: null,
    verified: true,
    category: "Books",
    district: "Bhopal",
    city: "Bhopal",
    state: "Madhya Pradesh",
    invoice: "",
    images: ["macmillanphysics.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Apple Watch Series 9",
    price: 45999,
    description: "Smartwatch with heart rate monitor and fitness tracking.",
    postingDate: new Date(),
    zipCode: "600015",
    seller: null,
    verified: true,
    category: "Electronics",
    district: "Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    invoice: "",
    images: ["applewatch9.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
];



export const moreDummyProducts = [
  {
    name: "Lenovo ThinkPad E14",
    price: 74999,
    description: "Durable business laptop with Intel i5, 16GB RAM, and 512GB SSD.",
    postingDate: new Date(),
    zipCode: "500032",
    seller: null,
    verified: true,
    category: "Laptops",
    district: "Ranga Reddy",
    city: "Hyderabad",
    state: "Telangana",
    invoice: "",
    images: ["thinkpadE14.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "OnePlus Nord 3",
    price: 34999,
    description: "5G smartphone with Dimensity 9000 chip and 120Hz AMOLED display.",
    postingDate: new Date(),
    zipCode: "110092",
    seller: null,
    verified: false,
    category: "Mobiles",
    district: "East Delhi",
    city: "New Delhi",
    state: "Delhi",
    invoice: "",
    images: ["oneplusnord3.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Reebok Training Shorts",
    price: 1599,
    description: "Lightweight shorts perfect for gym and sports activities.",
    postingDate: new Date(),
    zipCode: "560017",
    seller: null,
    verified: false,
    category: "Fashion",
    district: "Bangalore Urban",
    city: "Bangalore",
    state: "Karnataka",
    invoice: "",
    images: ["reebokshorts.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Samsung Galaxy Book 3",
    price: 104999,
    description: "Slim Windows laptop with AMOLED display and long battery life.",
    postingDate: new Date(),
    zipCode: "395007",
    seller: null,
    verified: true,
    category: "Laptops",
    district: "Surat",
    city: "Surat",
    state: "Gujarat",
    invoice: "",
    images: ["galaxybook3.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "LG 1.5 Ton Split AC",
    price: 42999,
    description: "Inverter air conditioner with fast cooling and energy saving.",
    postingDate: new Date(),
    zipCode: "600042",
    seller: null,
    verified: true,
    category: "Electronics",
    district: "Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    invoice: "",
    images: ["lgac.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Maruti Suzuki Swift 2020",
    price: 575000,
    description: "Well-maintained used car with low mileage and full service history.",
    postingDate: new Date(),
    zipCode: "226002",
    seller: null,
    verified: true,
    category: "Automobiles",
    district: "Lucknow",
    city: "Lucknow",
    state: "Uttar Pradesh",
    invoice: "",
    images: ["swiftt2020.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Wooden Bookshelf",
    price: 4999,
    description: "Solid wooden bookshelf with 5 compartments for storage.",
    postingDate: new Date(),
    zipCode: "682001",
    seller: null,
    verified: false,
    category: "Furniture",
    district: "Ernakulam",
    city: "Kochi",
    state: "Kerala",
    invoice: "",
    images: ["bookshelf.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Football - Adidas Brazuca",
    price: 2299,
    description: "FIFA-approved football with superior grip and durability.",
    postingDate: new Date(),
    zipCode: "751007",
    seller: null,
    verified: true,
    category: "Sports",
    district: "Bhubaneswar",
    city: "Bhubaneswar",
    state: "Odisha",
    invoice: "",
    images: ["brazuca.jpg"],
    requests: [],
    soldTo: null,
    isRental: true,
  },
  {
    name: "Casio Digital Piano CDP-S150",
    price: 34999,
    description: "88-key digital piano with weighted keys and multiple tones.",
    postingDate: new Date(),
    zipCode: "700098",
    seller: null,
    verified: true,
    category: "Musical Instruments",
    district: "South Kolkata",
    city: "Kolkata",
    state: "West Bengal",
    invoice: "",
    images: ["casios150.jpg"],
    requests: [],
    soldTo: null,
    isRental: true,
  },
  {
    name: "Honda City ZX 2019",
    price: 925000,
    description: "Automatic petrol variant in excellent condition, single owner.",
    postingDate: new Date(),
    zipCode: "141002",
    seller: null,
    verified: true,
    category: "Automobiles",
    district: "Ludhiana",
    city: "Ludhiana",
    state: "Punjab",
    invoice: "",
    images: ["hondacity2019.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Apple iPad Air 5th Gen",
    price: 56999,
    description: "M1-powered tablet with 10.9-inch Liquid Retina display.",
    postingDate: new Date(),
    zipCode: "122018",
    seller: null,
    verified: false,
    category: "Electronics",
    district: "Gurgaon",
    city: "Gurgaon",
    state: "Haryana",
    invoice: "",
    images: ["ipadair5.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Ray-Ban Aviator Sunglasses",
    price: 8999,
    description: "Classic metal frame aviator sunglasses with UV protection.",
    postingDate: new Date(),
    zipCode: "400104",
    seller: null,
    verified: true,
    category: "Fashion",
    district: "Mumbai Suburban",
    city: "Mumbai",
    state: "Maharashtra",
    invoice: "",
    images: ["raybanaviator.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Puma Sports T-shirt",
    price: 1599,
    description: "Breathable fabric t-shirt suitable for workouts.",
    postingDate: new Date(),
    zipCode: "560100",
    seller: null,
    verified: false,
    category: "Clothes",
    district: "Bangalore Urban",
    city: "Bangalore",
    state: "Karnataka",
    invoice: "",
    images: ["pumashirt.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Royal Enfield Classic 350",
    price: 185000,
    description: "Matte black edition with dual-channel ABS.",
    postingDate: new Date(),
    zipCode: "110030",
    seller: null,
    verified: true,
    category: "Automobiles",
    district: "South Delhi",
    city: "New Delhi",
    state: "Delhi",
    invoice: "",
    images: ["classic350.jpg"],
    requests: [],
    soldTo: null,
    isRental: true,
  },
  {
    name: "Philips Air Fryer HD9200",
    price: 7999,
    description: "Compact air fryer for healthy oil-free cooking.",
    postingDate: new Date(),
    zipCode: "411038",
    seller: null,
    verified: true,
    category: "Electronics",
    district: "Pune",
    city: "Pune",
    state: "Maharashtra",
    invoice: "",
    images: ["philipsairfryer.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Wilson Tennis Racket",
    price: 4999,
    description: "Professional tennis racket with carbon fiber frame.",
    postingDate: new Date(),
    zipCode: "160019",
    seller: null,
    verified: true,
    category: "Sports",
    district: "Chandigarh",
    city: "Chandigarh",
    state: "Punjab",
    invoice: "",
    images: ["wilsontennis.jpg"],
    requests: [],
    soldTo: null,
    isRental: true,
  },
  {
    name: "Office Ergonomic Chair",
    price: 10999,
    description: "Adjustable office chair with lumbar support and breathable mesh.",
    postingDate: new Date(),
    zipCode: "641004",
    seller: null,
    verified: true,
    category: "Furniture",
    district: "Coimbatore",
    city: "Coimbatore",
    state: "Tamil Nadu",
    invoice: "",
    images: ["officechair.jpg"],
    requests: [], 
    soldTo: null,
    isRental: false,
  },
  {
    name: "Acoustic Drum Kit - Pearl Roadshow",
    price: 42999,
    description: "5-piece drum set ideal for beginners and practice.",
    postingDate: new Date(),
    zipCode: "700029",
    seller: null,
    verified: false,
    category: "Musical Instruments",
    district: "Kolkata",
    city: "Kolkata",
    state: "West Bengal",
    invoice: "",
    images: ["pearldrum.jpg"],
    requests: [],
    soldTo: null,
    isRental: true,
  },
  {
    name: "Mahindra XUV700 2022",
    price: 1899000,
    description: "Luxury SUV with ADAS and panoramic sunroof.",
    postingDate: new Date(),
    zipCode: "500081",
    seller: null,
    verified: true,
    category: "Automobiles",
    district: "Hyderabad",
    city: "Hyderabad",
    state: "Telangana",
    invoice: "",
    images: ["xuv700.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Samsung Galaxy Watch 6",
    price: 29999,
    description: "Smartwatch with health tracking and AMOLED display.",
    postingDate: new Date(),
    zipCode: "302004",
    seller: null,
    verified: true,
    category: "Electronics",
    district: "Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    invoice: "",
    images: ["galaxywatch6.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Adidas Backpack",
    price: 2499,
    description: "Durable and water-resistant backpack for daily use.",
    postingDate: new Date(),
    zipCode: "380006",
    seller: null,
    verified: false,
    category: "Fashion",
    district: "Ahmedabad",
    city: "Ahmedabad",
    state: "Gujarat",
    invoice: "",
    images: ["adidasbackpack.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Guitar Amplifier - Marshall MG10G",
    price: 8999,
    description: "10W portable amplifier ideal for practice sessions.",
    postingDate: new Date(),
    zipCode: "700037",
    seller: null,
    verified: true,
    category: "Musical Instruments",
    district: "Kolkata",
    city: "Kolkata",
    state: "West Bengal",
    invoice: "",
    images: ["marshallamp.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "HP LaserJet Pro MFP",
    price: 17999,
    description: "All-in-one printer with wireless printing and scanning.",
    postingDate: new Date(),
    zipCode: "600089",
    seller: null,
    verified: true,
    category: "Electronics",
    district: "Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    invoice: "",
    images: ["hplaserjet.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Allen Solly Blazer",
    price: 6999,
    description: "Formal navy-blue blazer made from premium wool blend.",
    postingDate: new Date(),
    zipCode: "110048",
    seller: null,
    verified: false,
    category: "Clothes",
    district: "New Delhi",
    city: "New Delhi",
    state: "Delhi",
    invoice: "",
    images: ["allensollyblazer.jpg"],
    requests: [],
    soldTo: null,
    isRental: false,
  },
  {
    name: "Hero HF Deluxe 2021",
    price: 64000,
    description: "Economical commuter bike in mint condition.",
    postingDate: new Date(),
    zipCode: "826001",
    seller: null,
    verified: true,
    category: "Automobiles",
    district: "Dhanbad",
    city: "Dhanbad",
    state: "Jharkhand",
    invoice: "",
    images: ["herohfdeluxe.jpg"],
    requests: [],
    soldTo: null,
    isRental: true,
  },
];
